email:
  #服务器
  mailHost: smtp.163.com
  #端口号
  mailPort: 25
  #邮箱账号
  mailUsername: lcydorom@163.com
  #邮箱授权码
  mailPassword: xueyu1954
  #时间延迟
  mailTimeout: 25000
  #发送人
  mailFrom: lcydorom@163.com
  #发件人
  personal: 黑白色调
  #主题
  subject: ***
